name: Documentation checks

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './**/*.md'
          fail: true
